# pyproject.toml
[project]
name = "smallest-python"
version = "1.0.0"
description = "Official Python client for the Smallest AI API"
authors = [
    {name = "Smallest", email = "info@smallest.ai"},
]
dependencies = [
    "aiohttp",
    "aiofiles",
    "requests",
    "num2words",
    "sacremoses",
    "pydub",
    "websockets",
    "websocket-client"
]

[project.optional-dependencies]
test = [
    "jiwer",
    "httpx",
    "pytest",
    "pytest-asyncio",
    "deepgram-sdk",
    "python-dotenv"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# Add this section to make the package importable
[tool.setuptools.packages.find]
where = ["."]
include = ["smallest*"]
